export async function fetchLeadsFromDB() {
  return [
    { id: 1, name: "Jorge Ruiz", status: "Pending", createdAt: "2023-10-01", country: "Mexico" },
    { id: 2, name: "Maria Garcia", status: "Pending", createdAt: "2023-10-02", country: "Brazil" },
    { id: 3, name: "John Doe", status: "Pending", createdAt: "2023-10-03", country: "South Korea" },
    { id: 4, name: "Jane Smith", status: "Pending", createdAt: "2023-10-04", country: "Russia" },
    { id: 5, name: "Alice Johnson", status: "Pending", createdAt: "2023-10-05", country: "United Kingdom" },
    { id: 6, name: "Bob Brown", status: "Pending", createdAt: "2023-10-06", country: "Canada" },
    { id: 7, name: "Charlie Davis", status: "Pending", createdAt: "2023-10-07", country: "Australia" },
    { id: 8, name: "Diana Evans", status: "Pending", createdAt: "2023-10-08", country: "India" },
    { id: 9, name: "Ethan Foster", status: "Pending", createdAt: "2023-10-09", country: "Germany" },
    { id: 10, name: "Fiona Green", status: "Pending", createdAt: "2023-10-10", country: "France" },
    { id: 11, name: "George Harris", status: "Pending", createdAt: "2023-10-11", country: "Italy" },
    { id: 12, name: "Hannah Ivers", status: "Pending", createdAt: "2023-10-12", country: "Spain" },
    { id: 13, name: "Ian Johnson", status: "Pending", createdAt: "2023-10-13", country: "Netherlands" },
    { id: 14, name: "Jack King", status: "Pending", createdAt: "2023-10-14", country: "Sweden" },
    { id: 15, name: "Kathy Lee", status: "Pending", createdAt: "2023-10-15", country: "Norway" },
    { id: 16, name: "Liam Martinez", status: "Pending", createdAt: "2023-10-16", country: "Finland" },
    { id: 17, name: "Mia Nelson", status: "Pending", createdAt: "2023-10-17", country: "Denmark" },
    { id: 18, name: "Noah O'Brien", status: "Pending", createdAt: "2023-10-18", country: "Ireland" },
    { id: 19, name: "Olivia Parker", status: "Pending", createdAt: "2023-10-19", country: "Belgium" },
    { id: 20, name: "Paul Quinn", status: "Pending", createdAt: "2023-10-20", country: "Switzerland" },
    { id: 21, name: "Quinn Roberts", status: "Pending", createdAt: "2023-10-21", country: "Austria" },
    { id: 22, name: "Rachel Smith", status: "Pending", createdAt: "2023-10-22", country: "Portugal" },
    { id: 23, name: "Sam Taylor", status: "Pending", createdAt: "2023-10-23", country: "Greece" },
    { id: 24, name: "Tina Underwood", status: "Pending", createdAt: "2023-10-24", country: "Hungary" },
    { id: 25, name: "Ursula Vance", status: "Pending", createdAt: "2023-10-25", country: "Czech Republic" },
    { id: 26, name: "Victor White", status: "Pending", createdAt: "2023-10-26", country: "Poland" },
    { id: 27, name: "Wendy Young", status: "Pending", createdAt: "2023-10-27", country: "Slovakia" },
    { id: 28, name: "Xander Zane", status: "Pending", createdAt: "2023-10-28", country: "Slovenia" },
    { id: 29, name: "Yara Adams", status: "Pending", createdAt: "2023-10-29", country: "Croatia" },
    { id: 30, name: "Zoe Baker", status: "Pending", createdAt: "2023-10-30", country: "Lithuania" }
  ];
}